# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PCloud API Python package tests & linting

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
      max-parallel: 1
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup firefox
      uses: browser-actions/setup-firefox@5914774dda97099441f02628f8d46411fcfbd208
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-rerunfailures==15.0 pytest-cov==7.0.0 pytest-timeout==2.4.0
        pip install -e ".[test]"
        playwright install
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest src --cov=src/pcloud --cov-report=xml --cov-branch --cov-config=.coveragerc --capture=no -v --timeout=600 --reruns 3 --reruns-delay 5
      env:
        PCLOUD_USERNAME: ${{ secrets.PCLOUD_USERNAME }}
        PCLOUD_PASSWORD: ${{ secrets.PCLOUD_PASSWORD }}
        PCLOUD_OAUTH2_CLIENT_ID: ${{ secrets.PCLOUD_OAUTH2_CLIENT_ID }}
        PCLOUD_OAUTH2_CLIENT_SECRET: ${{ secrets.PCLOUD_OAUTH2_CLIENT_SECRET }}
    - name: Analyze with SonarCloud
      uses: SonarSource/sonarqube-scan-action@689fb39b34b9aa95ebc5f8f119343ddd51542402
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
      with:
        args: 
          -Dsonar.projectKey=tomgross_pycloud
          -Dsonar.organization=tomgross-github
          -Dsonar.python.version=3
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.python.coverage.exclusions=**/tests/*


